### ISSUE TITLE
Cannot upload treatments from xDrip+ after upgrading to v15

### ISSUE THREAD

**Issue by IndrekHaav** [nightscout/cgm-remote-monitor#8120]
**Describe the bug**
After upgrading Nightscout to v15.0.0, treatments entered in xDrip+ no longer appear in Nightscout. The following error shows up in system logs:

```
Oct 20 07:32:32 nightscout node[15154]: TypeError: api(...).save is not a function
Oct 20 07:32:32 nightscout node[15154]:     at Function.save (/opt/nightscout/lib/server/treatments.js:163:11)
Oct 20 07:32:32 nightscout node[15154]:     at /opt/nightscout/lib/api/treatments/index.js:196:22
Oct 20 07:32:32 nightscout node[15154]:     at Layer.handle [as handle_request] (/opt/nightscout/node_modules/express/lib/router/layer.js:95:5)
Oct 20 07:32:32 nightscout node[15154]:     at next (/opt/nightscout/node_modules/express/lib/router/route.js:137:13)
Oct 20 07:32:32 nightscout node[15154]:     at check (/opt/nightscout/lib/authorization/index.js:268:9)
Oct 20 07:32:32 nightscout node[15154]:     at runMicrotasks (<anonymous>)
Oct 20 07:32:32 nightscout node[15154]:     at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

Other data like BG readings get uploaded without issue.

**To Reproduce**
1. Enter new treatment in xDrip+
2. Wait for it to show up in Nightscout
3. Observe that it does not show up

**Expected behavior**
Treatments are uploaded to Nightscout and visible in the web UI as in previous versions.

**Your setup information**
- Nightscout v15.0.0
- Dexcom One, connected to Samsung phone running xDrip+, which is connected to Nightscout
- Issue is not browser-specific

**Comment by WesSec** [comment]
Rollback to 14.2.6 seemed to work for me without any issues/loss of data. After the rollback i did a backfill (under advanced settings in the nightscout settings in xdrip+)

**Comment by sulkaharo** [comment]
How are you hosting Nightscout? Curious if you made a full redeploy of the dependencies.

**Comment by WesSec** [comment]
I'm selfhosting via the docker container, so currently on `nightscout/cgm-remote-monitor:14.2.6` . My mongo uses the :latest tag and i did not change anything there.

**Comment by sulkaharo** [comment]
Right. You need to figure out how to update the node dependencies inside the container. That error basically implies the Mongo driver Nightscout is trying to learn doesn't match the expected version.

**Comment by IndrekHaav** [comment]
> How are you hosting Nightscout? Curious if you made a full redeploy of the dependencies.

I have Nightscout running in a Debian 12 LXC container. I also updated Node.js to v16, MongoDB is at v4.4. I did run `npm install` after pulling the v15.0.0 code from Github.

**Comment by bewest** [comment]
Duplicate? https://github.com/nightscout/cgm-remote-monitor/issues/8114

**Comment by IndrekHaav** [comment]
Not sure. I did update to v15.0.1 but that didn't solve my issue. Editing profiles seemed to work, but I didn't try it on v15.0.0 before updating.

**Comment by IndrekHaav** [comment]
I may have spoken too soon. Some treatments did show up after I manually sent older data from xDrip+ (as @WesSec mentioned in their first comment), perhaps I just didn't wait long enough.

I'll see how it behaves during normal use.

**Comment by IndrekHaav** [comment]
Okay, looks like it's working with v15.0.1 after all. Sorry for the confusion.

**Comment by thedewi** [comment]
This is still an issue because:
- No GitHub Release has happened since this was fixed
- The documentation still directs people to install the last GitHub Release - https://nightscout.github.io/update/update/
